/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:01634763-d130-4e32-b3a1-b1d2a1317673",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_DwNKdHmA7",
    "aws_user_pools_web_client_id": "453vllgsjbc83i4dpjnd65mq2g",
    "oauth": {}
};


export default awsmobile;
